### ISSUE TITLE
Change y-axis limits?

### ISSUE THREAD

**Issue by pmk2020** [juliedwhite/miamiplot#3]
Hi Julie, 
This is a great package! Is there a way I can change the limits of y-axis? My plot is getting cut at -log(pvalue) = 5 which makes sense since I dont have p-values lower than that but I would like to have slightly longer axis. 

Thanks, 
Pooja.

**Comment by juliedwhite** [comment]
Hey Pooja, 
Thanks! There's a couple of ways to do this, I think. 

1. You could make the miami plot from scratch. I've made a tutorial for this in one of the vignettes: `vignette(topic = "scratch_miamiplots", package = "miamiplot")`. In the **Plotting** section, for the upper plot you would change the line `scale_y_continuous(limits = c(0, maxp), expand = expansion(mult = c(0.02, 0)))` and either modify the limits with `maxp + however much you want` or modify the expansion with `expansion(mult = c(0.02, whatever multiplier you want)))`. For the lower plot, you would modify: `scale_y_reverse(limits = c(maxp, 0), expand = expansion(mult = c(0, 0.02)))` in a similar fashion, either adding a set value to `maxp` or changing the expansion factor. But, this might be pretty intensive for you. 
2. You could modify your version of the package. This would involve something along the lines of `fix(ggmiami)` and making the same changes as above. Full disclosure, I don't do this often, so I'm not 100% sure all the steps of this one, besides knowing that it's possible. 
3. About how much do you want to expand the axis? If it's not much, I wouldn't mind modifying the package from my end to add a little padding.

**Comment by pmk2020** [comment]
Thanks, Julie! I used the scratch vignette and that worked. It also gives me option to play around with font sizes and margins.
